name: "Podcast Generator"
author: "Xavier Ramos"
description: "This is a description"
runs: 
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
input:
  email:
    description: The persons email
    required: true
    #default: ${{ github.actor }}@localhost
  name:
    description: The persons name
    required: true
    #default: ${{ github.actor }}
